---
title: "**MÁS ALLÁ DE LA CRONOLOGÍA, USO DE LA INFERENCIA BAYESIANA PARA EVALUAR HIPÓTESIS EN ARQUEOLOGÍA**"
author: 
  - ERIK OTÁROLA-CASTILLO^1^*, 
  - MELISSA G. TORQUATO^1^,
  - JESSE WOLFHAGEN^1^,
  - MATTHEW E. HILL, JR.^2^,
  - AND CAITLIN E. BUCK^3^
  - ^1^Department of Anthropology, Purdue University, West Lafayette, Indiana, USA
  - ^2^Department of Anthropology, University of Iowa, Iowa City, Iowa, USA
  - ^3^School of Mathematics and Statistics, University of Sheffield, Sheffield, UK
  - " "
  - "**Preimpresión del manuscrito aceptado para publicación por el jornal Advances in Archaeological Practice.**"
  - " "
  - "*Autor correspondiente:"
  -   "email: eoc@purdue.edu"
date: 
  - " "
  - "*Última versión de R Markdown compilada el `r format(Sys.time(), '%A %B %d %Y, %X, %Z')`*"
  - " "
indent: yes
header-includes:
    - \usepackage{setspace}\doublespacing
    - \usepackage[labelfont=bf,width=1\textwidth,justification=raggedright,singlelinecheck=false]{caption}
    - \captionsetup[figure]{labelfont=bf}
    - \usepackage[pagewise]{lineno}
output: 
  pdf_document: 
    latex_engine: xelatex
    keep_md: false
  word_document: default
  html_document: default
link-citations: yes
bibliography: beyondchronologylibrary.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
options(kableExtra.auto_format = FALSE)
library(kableExtra)
library(dplyr)
library(knitr)
library(HDInterval)
library(ggplot2)
library(tidyr)
library(ggrepel)
library(ggtext)
```
\newpage
## RESUMEN

```{r child= "rmd_files/0_RESUMEN.Rmd"}

```

## INTRODUCCIÓN

```{r child= "rmd_files/1_INTRODUCCIÓN.Rmd"}

```

## LA CULTURA MONICO: UNA APLICACIÓN SIMPLIFICADA DE LAS ESTADÍSTICAS BAYESIANAS


```{r child= "rmd_files/2_UNA_APLICACIÓN_SIMPLIFICADA_DE_ESTADÍSTICAS_BAYESIANAS.Rmd"}

```

## QUE ES EL TEOREMA DE BAYES

```{r child= "rmd_files/3_QUÉ_ES_BAYES_TEOREMA.Rmd"}

```

## VINCULACIÓN DEL TEOREMA DE BAYES A DATOS E HIPÓTESIS

```{r child= "rmd_files/4_VINCULACION_DEL_TEOREMA_BAYES_A_LOS_DATOS_E_HIPOTESIS.Rmd"}

```

## CONCLUSIONES

```{r child= "rmd_files/5_CONCLUSIONES.Rmd"}

```

## AGRADECIMIENTOS

```{r child= "rmd_files/6_AGRADECIMIENTOS.Rmd"}

```




