---
output:
  pdf_document: default
  html_document: default
---
La inferencia bayesiana tiene ventajas para los arqueólogos que se extienden mucho más allá del ámbito de la calibración por radiocarbono y el modelado cronológico. El marco NHST ha servido bien a los arqueólogos durante muchos años, pero tiene limitaciones. Desafortunadamente, NHST basa la inferencia solo en datos nuevos debido a su estructura inherente. Su lenguaje y suposiciones pueden ser intrincados y confusos, y el planteamiento no puede utilizarse para comparar directamente múltiples hipótesis de trabajo. La inferencia bayesiana supera muchos de estos problemas para los arqueólogos. En muchos sentidos, los arqueólogos a menudo analizan los problemas utilizando un marco bayesiano sin saber que lo están haciendo y sin utilizar un marco probabilístico formal. Al igual que el arqueólogo bayesiano de nuestra parábola, la mayoría de los arqueólogos no forman inferencias sobre el pasado utilizando nuevos datos aislados del cuerpo de conocimiento existente. En cambio, actualizamos continuamente nuestro conocimiento previo con nueva evidencia para tomar decisiones, formar opiniones y generar conclusiones. La ventaja de la inferencia bayesiana sobre el NHST es que ofrece a los arqueólogos 1) un conjunto de herramientas más natural para aprender de los datos, 2) un lenguaje sencillo para hacer que las hipótesis sean cuantificables, explícitas y transparentes, y 3) la capacidad de utilizar la probabilidad para comparar múltiples hipótesis y realizar evaluación adicional.

En consecuencia, *el planteamiento bayesiano representa un cambio de paradigma en la inferencia arqueológica*. Las estadísticas bayesianas ofrecen un marco inferencial coherente que describe explícitamente la forma en que la información previa de uno se actualiza con nuevos datos para producir el estado actual del conocimiento. El proceso ayuda a evaluar el grado en que la evidencia actual y la nueva respaldan las hipótesis. Esto puede llevarse a cabo iterativamente hasta que haya una cantidad deseable de confianza (o falta de ella) en la precisión de una hipótesis. En este contexto, el marco bayesiano se asemeja a un proceso de aprendizaje similar a la investigación científica. Por ejemplo, los arqueólogos actualizan continuamente su conocimiento y grado de creencia en hipótesis utilizando nueva información recopilada a través de múltiples métodos de recopilación de datos, que incluyen excavación, estudio, experimentación, laboratorio y otras actividades analíticas.

Un número cada vez mayor de arqueólogos está utilizando estadísticas bayesianas para calibrar fechas de radiocarbono, construir cronologías y evaluar sus hipótesis sobre el pasado. La popularidad del software bayesiano relacionado con la cronología ha hecho que la inferencia bayesiana en ese contexto sea una operación simple, lo que significa que la mayoría de los usuarios encontrarán el software fácil de operar sin una comprensión básica de la lógica de la inferencia bayesiana y sus tres componentes fundamentales: la verosimilitud, la previa y la posterior. Además, sin esa comprensión fundamental, el poder analítico de las estadísticas bayesianas, más allá de la construcción de la cronología, puede no ser obvio, lo que ralentiza en lugar de mejorar la adopción más general. 

Para mitigar este problema, este documento destaca cómo los arqueólogos pueden utilizar la inferencia bayesiana para plantear cuestiones complejas a través de un ejemplo ficticio simple. Este planteamiento permite a los arqueólogos evaluar, comparar y actualizar sus hipótesis directamente, utilizando el peso de la evidencia y un proceso sencillo. Consideramos que este es uno de los impactos más significativos del paradigma bayesiano. Además, la inferencia bayesiana requiere que los arqueólogos se vuelvan conscientes y transparentes sobre la información previa y actual para los análisis estadísticos dentro de una estructura probabilística. El marco incorpora explícitamente toda la información (previa y actual) para permitir una comprensión más completa de un problema.

Como resultado, las aplicaciones de este método conducen a la replicación, lo que permite que otros científicos arqueológicos las mejoren. Bajo esta luz, la inferencia bayesiana encaja con los esfuerzos en curso para promover métodos de ciencia abierta y datos abiertos en la investigación arqueológica. Este contexto anima a los investigadores a delinear todo el proceso lógico que subyace a sus resultados. Debido a sus ventajas, creemos que la inferencia bayesiana está bien posicionada para convertirse en un planteamiento estándar para evaluar hipótesis cuantitativas en arqueología. 